config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
  resources :hashtags, only: :show, param: :name
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true
  has_and_belongs_to_many :hashtags

  validates :text, :user, presence: true, length: { maximum: 255 }

  before_save :set_hashtags
  after_commit :delete_independent_hashtags

  def set_hashtags
    self.hashtags = "#{text} #{answer}".
                      scan(HASHTAG_REGEX).
                      map { |ht| ht.downcase.delete('#') }.
                      uniq.
                      map { |ht| Hashtag.find_or_create_by(name: ht) }
  end

  def delete_independent_hashtags
    Hashtag.includes(:questions).where(questions: { id: nil }).destroy_all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: :create

  def edit; end

  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if check_captcha(@question) && @question.save
      redirect_to user_url(@question.user), notice: I18n.t('controllers.questions.created')
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_url(@question.user), notice: I18n.t('controllers.questions.updated')
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: I18n.t('controllers.questions.destroyed')
  end

  private

  def question_params
    if current_user.present? && params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def check_captcha(model)
    current_user.present? || verify_recaptcha(model: model)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def author(question)
    from_whom = if question.author.present?
                  link_to "@#{question.author.username}", user_url(question.author)
                else
                  'анонимного пользователя'
                end
    "Вопрос от #{from_whom}"
  end

  def question_time(question)
    l(question.created_at, format: '%-d %B %Y %k:%M')
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end

  def replace_hashtags_with_links(text)
    text.gsub(HASHTAG_REGEX) { |ht| link_to ht, hashtag_url(ht.delete('#').downcase)}.html_safe
  end
end

app/views/questions/_form.html.haml
.form
  = form_for(@question) do |f|
    = render 'partials/error_messages', object: f.object
    = f.hidden_field :user_id
    .form-field
      = f.label :text, class: 'form-label'
      = f.text_area :text, class: 'form-textarea'
    - if current_user.present? && current_user == @question.user
      .form-field
        = f.label :answer, class: 'form-label'
        = f.text_area :answer, class: 'form-textarea'
    .form-action.buffer-both
      - if current_user.present?
        = f.submit 'Сохранить', class: 'button button-dark button-small'
      - else
        = invisible_recaptcha_tags text: '¿Спроси вопрос?', class: 'button button-dark button-small'
      = link_to 'Вернуться', user_path(@question.user), class: 'button button-dark button-small'

app/views/questions/_question.html.haml
.question
  .question-content
    .question-text.text-lead
      = replace_hashtags_with_links(question.text)
    - if question.answer.present?
      .question-answer.text-lead
        = replace_hashtags_with_links(question.answer)
    .question-info
      = author(question).html_safe
    .question-info
      = question_time(question)
  - if question.user == current_user
    - edit_icon = question.answer.blank? ? 'reply' : 'pencil'
    .question-actions
      = link_to fa_icon(edit_icon), edit_question_path(question)
      = link_to fa_icon('trash-o'), question_path(question), method: :delete, data: { confirm: t('are_you_sure') }

app/views/questions/_question_blank.html.haml
.question
  .question-content
    .question-text.text-lead
      %p Пока что пользователю вопросов не задавали.
      %p Почему мы бы Вам не ¿задать вопрос?

app/views/questions/edit.html.haml
.container.content-wrapper.buffer-both
  %h1.title-medium
    Вопрос
  .column-1-2
    = render 'form'