config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
  resources :hashtags, only: :show, param: :name
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  ITERATIONS = 20_000.freeze
  DIGEST = OpenSSL::Digest::SHA256.new.freeze
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  VALID_USERNAME_REGEX = /\A\w+\z/.freeze
  VALID_COLOR_REGEX = /\A#([\da-f]{3}){1,2}\z/i.freeze
  MAX_NAME_LENGTH = 40.freeze

  attr_accessor :password

  has_many :questions, dependent: :destroy
  validates :username, presence: true, uniqueness: true,
                       length: { maximum: MAX_NAME_LENGTH },
                       format: { with: VALID_USERNAME_REGEX }
  validates :email, presence: true, uniqueness: true,
                    format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true
  validates :password, presence: true, on: :create
  validates_confirmation_of :password
  validates :bgcolor, :fontcolor, :bordercolor, format: { with: VALID_COLOR_REGEX }, allow_blank: true
  before_validation :downcase_email_and_username
  before_save :encrypt_password

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    email.downcase!
    user = find_by(email: email)
    return nil unless user.present?

    hashed_password = User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password,
                                                                     user.password_salt,
                                                                     ITERATIONS,
                                                                     DIGEST.length,
                                                                     DIGEST))
    return user if user.password_hash == hashed_password
    nil
  end

  private

  def encrypt_password
    if password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      self.password_hash = User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password,
                                                                          password_salt,
                                                                          ITERATIONS,
                                                                          DIGEST.length,
                                                                          DIGEST))
    end
  end

  def downcase_email_and_username
    email.downcase! if email.present?
    username.downcase! if username.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Pagy::Backend

  before_action :load_user, except: [:index, :new, :create]
  before_action :redirect_current_user, only: [:new, :create]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all.order(:id)
    @hashtags = Hashtag.all.order(:name)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: I18n.t('controllers.users.created')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  def show
    @questions = @user.questions
    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count

    @pagy, @questions = pagy(@user.questions.order(created_at: :desc), items: 3)
    @new_question = @user.questions.build
  end

  def destroy
    @user.destroy
    redirect_to root_url, notice: I18n.t('controllers.users.destroyed')
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :bgcolor,
                                 :fontcolor, :bordercolor)
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def authorize_user
    reject_user unless @user == current_user
  end

  def redirect_current_user
    redirect_to root_url, alert: I18n.t('controllers.users.logged_in') if current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_url 'avatar.png'
    end
  end

  def bgcolor(user)
    if user.bgcolor.present?
      user.bgcolor
    else
      '#ecb8a5'
    end
  end

  def fontcolor(user)
    if user.fontcolor.present?
      user.fontcolor
    else
      '#904c77'
    end
  end

  def bordercolor(user)
    if user.bordercolor.present?
      user.bordercolor
    else
      '#957d95'
    end
  end
end

app/views/users/_form.html.haml
.form
  = form_for @user do |f|
    = render 'partials/error_messages', object: f.object
    .form-field
      = f.label :email, class: 'form-label'
      = f.text_field :email, class: 'form-text-field'
    .form-field
      = f.label :username, class: 'form-label'
      = f.text_field :username, class: 'form-text-field', id: 'username'
    .form-field
      = f.label :name, class: 'form-label'
      = f.text_field :name, class: 'form-text-field', id: 'name'
    - if current_user
      .form-field
        = f.label :avatar_url, class: 'form-label'
        = f.text_field :avatar_url, class: 'form-text-field', id: 'avatar_url'
      .form-field
        %input#default-colors.radio(name="colors" type="radio")
        %label(for="default-colors") Цвета по умолчанию
      .form-field
        %input#custom-colors.radio(name="colors" type="radio" checked="checked")
        %label(for="custom-colors") Цвета по выбору
      #color-fields
        .column-1-3
          .form-field
            = f.label :bgcolor, class: 'form-label'
            = f.color_field :bgcolor, value: bgcolor(@user), class: 'form-color-field', id: 'bgcolor'
        .column-1-3
          .form-field
            = f.label :fontcolor, class: 'form-label'
            = f.color_field :fontcolor, value: fontcolor(@user), class: 'form-color-field', id: 'fontcolor'
        .column-1-3
          .form-field
            = f.label :bordercolor, class: 'form-label'
            = f.color_field :bordercolor, value: bordercolor(@user), class: 'form-color-field', id: 'bordercolor'
    .form-field
      = f.label :password, class: 'form-label'
      = f.password_field :password, class: 'form-text-field'
    .form-field
      = f.label :password_confirmation, class: 'form-label'
      = f.password_field :password_confirmation, class: 'form-text-field'
    .form-action
      = f.submit yield(:submit_button), class: 'button button-small button-dark'
      - if current_user
        = link_to 'Удалить профиль', @user, method: :delete, data: { confirm: t('are_you_sure') }, class: 'button button-small button-dark'

app/views/users/edit.html.haml
- provide :submit_button, 'Обновить'
.container.content-wrapper.buffer-both
  .column-1-2
    %h1.title-medium
      Править профиль
    = render 'form'
  .column-1-2
    .preview
      %h1.title-medium.text-center
        Предпросмотр
      #preview-upper.user-header.text-center
        %h1#preview-name.title-medium
          = @user.name
        #preview-border.user-image-div
          = image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]', id: 'preview-avatar'
        %h2#preview-username.title-small.buffer-both
          @#{@user.username}
        .buffer-both
          Редактировать профиль
        .container.text-center
          .button.button-light
            ¿Есть вопрос?
      #preview-lower.user-details
        .user-statistics.container.text-center
          .column-1-3
            = t(:question, count: 21)
          .column-1-3
            = t(:unanswered, count: 20)
          .column-1-3
            = t(:answer, count: 1)

app/views/users/index.html.haml
.content-wrapper.buffer-both.text-center
  - unless @users.any?
    .buffer-both-large
      %p Здесь пока никого нет
      .buffer-top
        #{link_to 'Региструйтесь', sign_up_url, class: 'user-index-link'}, чтобы быть первым
  -else
    .buffer-both
      %h1.title-medium Наши пользователи
      - @users.each do |user|
        .users-list-item
          .user-image-div.user-image-div-small
            = link_to image_tag(user_avatar(user), class: 'user-image'), user_url(user)
      - if @hashtags.any?
        .buffer-both-large
          %h1.title-medium Хэштеги
          = render 'hashtags/hashtag'

app/views/users/new.html.haml
- provide :submit_button, 'Зарегистрироваться'
.container.content-wrapper.buffer-both
  %h1.title-medium
    Присоединяйся к нам!
  .column-1-2
    = render 'form'

app/views/users/show.html.haml
.user-header.text-center(style="background: #{bgcolor(@user)}; color: #{fontcolor(@user)}")
  %h1.title-medium
    = @user.name
  .user-image-div(style="border-color: #{bordercolor(@user)}")
    = image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]'
  %h2.title-small.buffer-both
    @#{@user.username}
  -if current_user == @user
    .buffer-both
      = link_to 'Редактировать профиль', edit_user_url(@user), style: "color: #{fontcolor(@user)}"
  .user-ask-button.container.text-center
    = link_to '¿Есть вопрос?', '', class: 'button button-light', id: 'ask-button'
.user-details(style="background: #{bgcolor(@user)}; color: #{fontcolor(@user)}")
  .user-statistics.container.text-center
    .column-1-3
      = t(:question, count: @questions_count)
    .column-1-3
      = t(:unanswered, count: @unanswered_count)
    .column-1-3
      = t(:answer, count: @answers_count)
#ask-form.user-question-form-div.column-1-4.column-1-4-right
  .user-question-form.buffer-both
    .form
      = form_for @new_question do |f|
        = f.hidden_field :user_id
        .form-field
          = f.label "Вопрос пользователю @#{@user.username}", class: 'form-label'
          = f.text_area :text, class: 'form-textarea'
        .form-action
          - if current_user.present?
            = submit_tag '¿Спроси вопрос?', class: 'button button-small button-dark'
          - else
            = invisible_recaptcha_tags text: '¿Спроси вопрос?', class: 'button button-small button-dark'
.column-3-4
  .user-questions.buffer-both
    .questions-list
      - if @questions.count.zero?
        = render partial: 'questions/question_blank'
      - else
        = render partial: 'questions/question', collection: @questions
  - unless @questions.count.zero?
    .questions-pagination
      = pagy_plain_responsive_nav(@pagy).html_safe